x <- read.csv(file = "/Users/topherkioschos/Desktop/Data/Oil_Prod.csv")
library("corrplot")
summary(x)
head(x)
tail(x)
class(x)
1:100
rep(1:10,5)
class(x$US)
class(x$Pennsylvania)
plot(x)
plot(x$US,x$New_Mexico)
hist(x$US)
tail(x)
na.omit(x)
complete.cases(x)
col(OIL)
cor(OIL, method = c("pearson"))
saveRDS(na.omit(x), file="y.RDS")
CREATE_FIGURE <- function(X,NAME,PATH="./Results",METHOD=NULL)
  COR <- cor(X,method=METHOD)
jpeg(filename="/Users/topherkioschos/Desktop/Data",height=7,width=6,units='in',res=300)
corrplot(COR,method="color")
IS_PRE_2014 <- OIL_ORIG$Date<'2014-01-01'
OIL_PRE2014 <- OIL[IS_PRE_2014,]
OIL_POST2014 <- OIL[!IS_PRE_2014,]
RANK <- sort(rank(-COR[,COL_WY]))
NMS <- names(RANK)
X <- names(X[,NMS])
CREATE_FIGURE(OIL_PRE2014,"Wyoming Pre-2014 Regional Correlation (pearson).jpeg")
CREATE_FIGURE(OIL_POST2014,"Wyoming Post-2014 Regional Correlation (pearson).jpeg")
CREATE_FIGURE(OIL_PRE2014,"Wyoming Pre-2014 Regional Correlation
(spearman).jpeg",METHOD="spearman")
CREATE_FIGURE(OIL_POST2014,"Wyoming Post-2014 Regional Correlation
(spearman).jpeg",METHOD="spearman")
dir.create("plots")
file.exists("plots")
!file.exists("plots")
if("plots")
ifelse("plots")
"/Users/topherkioschos/Desktop/Data/plots" <- paste0(PATH,"/",NAME)
jpeg(filename="plots",height=7,width=6,units='in',res=300)
corrplot(COR,method="color")
dev.off("plots")
COR <- cor("plots",method=Pearson)
RANK <- sort(rank(-COR[,COL_WY]))
NMS <- names(RANK)
"plots" <- names(X[,NMS])
CREATE_FIGURE(OIL_PRE2014,"/Users/topherkioschos/Desktop/Data/plots.jpeg",METHOD="spearman")
CREATE_FIGURE(OIL_POST2014,"/Users/topherkioschos/Desktop/Data/plots.jpeg",METHOD="spearman")

if(!file.exists("/Users/topherkioschos/Desktop/Data/plots.jpeg")){
  print("plots")
  dir.create(CREATE_FIGURE(OIL_POST2014,"/Users/topherkioschos/Desktop/Data/plots.jpeg",METHOD="pearson"))
}  else{
  print("Directory already exists. Reusing the existing
directory")
call(a,"plots")
call(b,"x")
call(c,"y")
call(d,"OIL(OG)")
